import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/app/ui/header";

export const runtime = "edge";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Next.js Sample",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased bg-blue-50 text-blue-900`}
			>
				<header className="bg-blue-600 p-4 border-b-4 border-blue-800">
					<Header />
				</header>

				<main className="p-8 max-w-4xl mx-auto bg-white border-2 border-blue-200 shadow-md rounded-lg">
					{children}
				</main>

				<footer className="text-center p-4 mt-8 bg-blue-600 text-white border-t-4 border-blue-800">
					<p>&copy; 2024 isksss</p>
				</footer>
			</body>
		</html>
	);
}
